# Generated by Django 5.1.4 on 2025-06-09 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AguaResidualTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConductividadMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cond1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cond2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cond3', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CroquisUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(max_length=255)),
                ('croquis', models.ImageField(blank=True, null=True, upload_to='croquis/')),
                ('comentario', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuerpoReceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('codigoPostal', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('colonia', models.CharField(max_length=255)),
                ('numeroExterior', models.CharField(blank=True, max_length=24, null=True)),
                ('calle', models.CharField(max_length=255)),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCustodia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrecuenciaMuestreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaOperacion', models.CharField(max_length=50)),
                ('numeroMuestrasSimples', models.CharField(max_length=50)),
                ('invervaloMinimo', models.CharField(max_length=50)),
                ('invervaloMaximo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ph2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ph3', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PlanMuestreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicial', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaInicial', models.DateField(blank=True, null=True)),
                ('final', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaFinal', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preservador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PreservadorUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePila', models.CharField(max_length=50)),
                ('apPaterno', models.CharField(max_length=50)),
                ('apMaterno', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SitioMuestreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('giroEmpresa', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaAireMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempAire1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tempAire2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tempAire3', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp3', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TiempoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo3', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDescarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VolumenMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volumen2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volumen3', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AguaResidualInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CroquisUbicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.croquisubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='MuestraHojaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('materiaFlotante', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('olor', models.CharField(blank=True, max_length=50, null=True)),
                ('solido', models.BooleanField(default=False)),
                ('lluvia', models.BooleanField(default=False)),
                ('condicion', models.CharField(blank=True, choices=[('soleado', 'Soleado'), ('nublado', 'Nublado'), ('medio_nublado', '1/2 Nublado')], max_length=50, null=True)),
                ('conductividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.conductividadmuestra')),
                ('ph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.phmuestra')),
                ('temperaturaAire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.temperaturaairemuestra')),
                ('temperatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.temperaturamuestra')),
                ('tiempoMuestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tiempomuestra')),
                ('volumenMuestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.volumenmuestra')),
            ],
        ),
        migrations.CreateModel(
            name='HojaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMuestra', models.CharField(max_length=50)),
                ('normaReferencia', models.CharField(max_length=50)),
                ('condicionMuestreo', models.BooleanField(max_length=50)),
                ('fechaMuestreo', models.DateField()),
                ('observacion', models.TextField(blank=True, max_length=255, null=True)),
                ('muestreador', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('aguaResidualInforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aguaresidualinforme')),
                ('muestraHojaCampo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.muestrahojacampo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=255)),
                ('nombreUsuario', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receptor')),
            ],
        ),
        migrations.CreateModel(
            name='CustodiaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.CharField(max_length=50)),
                ('puestoCargoContacto', models.CharField(blank=True, max_length=50, null=True)),
                ('celularContacto', models.CharField(blank=True, max_length=50, null=True)),
                ('correoContacto', models.EmailField(blank=True, max_length=50, null=True)),
                ('puntosMuestreoAutorizados', models.CharField(max_length=50)),
                ('modificacionOrdenTrabajo', models.BooleanField()),
                ('observacionesModificacion', models.TextField(blank=True, max_length=120, null=True)),
                ('asesoriaGestionAmbiental', models.BooleanField()),
                ('muestreoRequerido', models.CharField(max_length=50)),
                ('fechaFinal', models.DateField(blank=True, null=True)),
                ('horaFinal', models.TimeField(blank=True, null=True)),
                ('muestraCompuesta', models.BooleanField()),
                ('idMuestraCompuesta', models.CharField(blank=True, max_length=50, null=True)),
                ('muestraPuntual', models.BooleanField()),
                ('idMuestraPuntual', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=325, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estadocustodia')),
                ('ordenTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ordentrabajo')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prioridad')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receptor')),
            ],
        ),
        migrations.AddField(
            model_name='aguaresidualinforme',
            name='OrdenTrabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ordentrabajo'),
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacionCampo', models.CharField(max_length=50)),
                ('fechaMuestreo', models.DateField()),
                ('horaMuestreo', models.TimeField()),
                ('volumenCantidad', models.CharField(blank=True, max_length=50, null=True)),
                ('numeroContenedor', models.CharField(max_length=50)),
                ('origenMuestra', models.CharField(max_length=50)),
                ('idLaboratorio', models.CharField(blank=True, max_length=50, null=True)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contenedor')),
                ('custodiaExterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.custodiaexterna')),
                ('filtro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filtro')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matriz')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parametro')),
            ],
        ),
        migrations.CreateModel(
            name='PreservadorMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.muestra')),
                ('preservador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preservador')),
            ],
        ),
        migrations.AddField(
            model_name='muestra',
            name='preservador',
            field=models.ManyToManyField(through='core.PreservadorMuestra', to='core.preservador'),
        ),
        migrations.CreateModel(
            name='ProcedimientoMuestreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametroADeterminar', models.CharField(blank=True, max_length=50, null=True)),
                ('tipoMuestreo', models.BooleanField(default=False)),
                ('tipoAguaOtro', models.CharField(blank=True, max_length=50, null=True)),
                ('cuerpoReceptorOtro', models.CharField(blank=True, max_length=50, null=True)),
                ('cuerpoReceptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cuerporeceptor')),
                ('frecuenciaMuestreo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.frecuenciamuestreo')),
                ('materialUso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.materialuso')),
                ('preservadorUtilizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.preservadorutilizado')),
                ('recipiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.recipiente')),
                ('tipoAgua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipoagua')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoMuestreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacionPunto', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcionProceso', models.TextField(blank=True, max_length=255, null=True)),
                ('origenMuestra', models.CharField(blank=True, max_length=50, null=True)),
                ('aguaResidualOtro', models.CharField(blank=True, max_length=50, null=True)),
                ('horasOperacion', models.CharField(blank=True, max_length=50, null=True)),
                ('horasDescarga', models.CharField(blank=True, max_length=50, null=True)),
                ('frecuenciaDescarga', models.CharField(blank=True, max_length=50, null=True)),
                ('informacionProporcionada', models.CharField(blank=True, max_length=50, null=True)),
                ('aguaResidualTratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aguaresidualtratamiento')),
                ('tipoDescarga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipodescarga')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCustodia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregadoPor', models.CharField(max_length=100)),
                ('fechaEntrega', models.DateField()),
                ('horaEntrega', models.TimeField()),
                ('recibidoPor', models.CharField(max_length=100)),
                ('fechaEecepcion', models.DateField()),
                ('horaRecepcion', models.TimeField()),
                ('custodiaExterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.custodiaexterna')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('nombreServicio', models.CharField(max_length=255)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.metodo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('ordenTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ordentrabajo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='servicio',
            field=models.ManyToManyField(through='core.OrdenTrabajoServicio', to='core.servicio'),
        ),
        migrations.CreateModel(
            name='ProtocoloMuestreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aguaResidualInforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aguaresidualinforme')),
                ('planMuestreo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.planmuestreo')),
                ('procedimientoMuestreo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.procedimientomuestreo')),
                ('puntoMuestreo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.puntomuestreo')),
                ('sitioMuestreo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sitiomuestreo')),
            ],
        ),
    ]
